codecov:
  require_ci_to_pass: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default

coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 0.2%
    patch:
      default:
        target: 95%
        threshold: 0%

ignore:
  - "migrations/**"
  - "tests/**"
  - "wsgi.py"

