# Python 3 with PostgreSQL
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile    
    hostname: nyu
    container_name: nyu-project
    volumes:
      - ..:/app
      - ./logs:/var/log
    command: bash -c "sleep 10 && flask run --host=0.0.0.0 --port=5000"
    ports:
      - "8080:5000"
    environment:
      PORT: 5000
      FLASK_APP: wsgi:app
      FLASK_DEBUG: "True"
      GUNICORN_BIND: "0.0.0.0:5000"
      DATABASE_URI: postgresql+psycopg://postgres:postgres@postgres:5432/mydb
    networks:
      - dev
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  postgres:

networks:
  dev:
