---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone
spec:
  workspaces:
    - name: source
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: "main"
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        set -e
        git clone $(params.url) --branch $(params.revision) /workspace/source

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint
spec:
  workspaces:
    - name: source
  steps:
    - name: lint
      image: python:3.11-slim
      workingDir: $(workspaces.source.path)
      script: |
        pip install pylint flake8
        flake8 .
        pylint service || true

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: python:3.11-slim
      workingDir: $(workspaces.source.path)
      script: |
        pip install pytest
        pytest

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  workspaces:
    - name: source
  steps:
    - name: build
      image: alpine
      script: |
        #!/bin/sh
        echo "Build step placeholder. No actual image build performed."

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  workspaces:
    - name: source
  steps:
    - name: deploy
      image: alpine
      script: |
        #!/bin/sh
        echo "Deploy step placeholder. No actual deployment performed."

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: bdd
spec:
  workspaces:
    - name: source
  steps:
    - name: bdd
      image: alpine
      script: |
        #!/bin/sh
        echo "BDD tests placeholder."
