apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - description: The URL to github
      name: GIT_REPO
      type: string
    - default: master
      description: The reference
      name: GIT_REF
      type: string
    - default: promotions
      description: Name of the application
      name: APP_NAME
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.APP_NAME):latest'
      description: the name of the image to build
      name: IMAGE_NAME
      type: string
  tasks:
