name: CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11-slim

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python package dependencies
        run: |
          python -m pip install -U pip pipenv
          pipenv install --system --dev
      # - name: Linting
      #   run: |
      #     flake8 service tests --count --select=E9,F63,F7,F82 --show-source --statistics
      #     flake8 service tests --count --max-complexity=10 --max-line-length=127 --statistics
      #     pylint service tests --max-line-length=127
      - name: Run unit tests with PyTest
        env:
          DATABASE_URI: "postgresql+psycopg://postgres:pgs3cr3t@postgres:5432/postgres"
        run: pytest --pspec --cov=service --cov-fail-under=95 --cov-report=xml